apiVersion: v1
kind: Secret
metadata:
  name: iot-producer-secrets
  namespace: iot-monitoring
  labels:
    app: industrial-iot-producer
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  # echo -n 'your-db-password' | base64
  db-password: cGFzc3dvcmQxMjM=
  
  # Kafka SASL credentials (if needed)
  # echo -n 'kafka-username' | base64
  kafka-username: aW90LXVzZXI=
  # echo -n 'kafka-password' | base64  
  kafka-password: a2Fma2EtcGFzc3dvcmQ=
  
  # API keys for external services
  # echo -n 'your-api-key' | base64
  monitoring-api-key: bW9uaXRvcmluZy1hcGkta2V5
  
  # TLS certificates (if needed)
  tls-cert: LS0tLS1CRUdJTi...
  tls-key: LS0tLS1CRUdJTi...
